#!/bin/bash
 
# this function is called when Ctrl-C is sent
function trap_ctrlc ()
{

    # perform cleanup here
    echo "Ctrl-C caught...performing clean up"

    for i in "${!PIDS[@]}"; do
      ssh -AX akalaba@pc${addrId[i]}.emulab.net "sudo kill ${PIDS[i]}"
      echo "Killed ${names[i]}"
    done
 
    # exit shell script with error code 2
    # if omitted, shell script will continue execution
    exit 2
}
 
# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

# your script goes here
coordcmd="bin/coordinator -N 3 -ips '10.10.1.6,10.10.1.2,10.10.1.10'"

m1cmd="bin/master -port 7087 -addr '10.10.1.6'  -ips '10.10.1.9,10.10.1.8,10.10.1.7' -caddr '10.10.1.1' -nshrds 3"
m2cmd="bin/master -port 7088 -addr '10.10.1.2'  -ips '10.10.1.5,10.10.1.4,10.10.1.3' -caddr '10.10.1.1' -nshrds 3"
m3cmd="bin/master -port 7089 -addr '10.10.1.10'  -ips '10.10.1.13,10.10.1.12,10.10.1.11' -caddr '10.10.1.1' -nshrds 3"

s1r1cmd="bin/server -port 7070 -maddr '10.10.1.6' -mport 7087 -addr '10.10.1.9'"
s1r2cmd="bin/server -port 7071 -maddr '10.10.1.6' -mport 7087 -addr '10.10.1.8'"
s1r3cmd="bin/server -port 7072 -maddr '10.10.1.6' -mport 7087 -addr '10.10.1.7'"

s2r1cmd="bin/server -port 7073 -maddr '10.10.1.2' -mport 7088 -addr '10.10.1.5'"
s2r2cmd="bin/server -port 7074 -maddr '10.10.1.2' -mport 7088 -addr '10.10.1.4'"
s2r3cmd="bin/server -port 7075 -maddr '10.10.1.2' -mport 7088 -addr '10.10.1.3'"

s3r1cmd="bin/server -port 7076 -maddr '10.10.1.10' -mport 7089 -addr '10.10.1.13'"
s3r2cmd="bin/server -port 7077 -maddr '10.10.1.10' -mport 7089 -addr '10.10.1.12'"
s3r3cmd="bin/server -port 7078 -maddr '10.10.1.10' -mport 7089 -addr '10.10.1.11'"


c1cmd="bin/client-ms-test -caddr "10.10.1.1" -pid 100 -fo 10 -w 50 -c 1 -k 1000000000"
#c2cmd="bin/client-ms-test -caddr "10.10.1.1" -pid 200 -fo 2 -w 50 -c 1 -k 1000000000"

precursor="cd ~/MDLin; nohup "
postcursormdl=" -mdl true </dev/null >/dev/null 2>outerr.txt & echo \$!"
postcursorbasic=" </dev/null >/dev/null 2>outerr.txt & echo \$!"

PIDS=()
addrId=(477 419 427 440 474 439 429 479 432 473 480 420 423 475 430) #434 422 438)
cmds=("$coordcmd" "$m1cmd" "$m2cmd" "$m3cmd" "$s1r1cmd" "$s1r2cmd" "$s1r3cmd" "$s2r1cmd" "$s2r2cmd" "$s2r3cmd" "$s3r1cmd" "$s3r2cmd" "$s3r3cmd" "$c1cmd")
names=(coord m1 m2 m3 s1r1 s1r2 s1r3 s2r1 s2r2 s2r3 s3r1 s3r2 s3r3 c1 c2)
for ((i = 0; i < ${#cmds[@]}; i++)); do
  echo $i
  if [ "$1" == "mdl" ] && [ $i -gt 3 ]
  then
    read -r somevar < <(ssh -AX akalaba@pc${addrId[i]}.emulab.net $precursor${cmds[i]}$postcursormdl)
    echo "Setup MDL ${names[i]}..."
  else
    read -r somevar < <(ssh -AX akalaba@pc${addrId[i]}.emulab.net $precursor${cmds[i]}$postcursorbasic)
    echo "Setup BASIC ${names[i]}..."
  fi
  PIDS[i]=$somevar
  sleep 3
done

echo "Done!"
sleep 1000000000
