#!/bin/bash
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(1200000)/ns := int64(800000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(800000)/ns := int64(400000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(400000)/ns := int64(200000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(200000)/ns := int64(100000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(100000)/ns := int64(50000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(50000)/ns := int64(25000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(25000)/ns := int64(12500)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(12500)/ns := int64(6250)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(6250)/ns := int64(3000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(3000)/ns := int64(1000)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(1000)/ns := int64(500)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(500)/ns := int64(250)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(250)/ns := int64(100)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

sed -i 's/ns := int64(100)/ns := int64(50)/g' src/monitoring_app_client/main.go
make
python3 ./scripts/run_multiple_experiments.py ./experiments/osdi25/test-monitor-app3.json

