#!/bin/bash
 
# this function is called when Ctrl-C is sent
function trap_ctrlc ()
{
    # perform cleanup here
    echo "Ctrl-C caught...performing clean up"
 
    echo "Doing cleanup"
    sudo kill $COORD
    echo "Killed coordinator"
    sudo kill $M1
    echo "Killed master1"
    sudo kill $M2
    echo "Killed master2"
    sudo kill $M3
    echo "Killed master3"
    sudo kill $L1
    echo "Killed shard1 leader"
    sudo kill $L2
    echo "Killed shard2 leader"
    sudo kill $L3
    echo "Killed shard3 leader"
    sudo kill $R12
    echo "Killed shard1 rep2"
    sudo kill $R13
    echo "Killed shard1 rep3"
    sudo kill $R22
    echo "Killed shard2 rep2"
    sudo kill $R23
    echo "Killed shard2 rep3"
    sudo kill $R32
    echo "Killed shard3 rep2"
    sudo kill $R33
    echo "Killed shard3 rep3"
    sudo kill $CLIENT1
    echo "Killed client1"
    sudo kill $CLIENT2
    echo "Killed client2"
 
    # exit shell script with error code 2
    # if omitted, shell script will continue execution
    exit 2
}
 
# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2
 
# your script goes here
bin/coordinator -N 3 &
export COORD=$!
bin/master -nshrds 3 &
export M1=$!
sleep 2
bin/master -port 7088 -nshrds 3 &
export M2=$!
sleep 2
bin/master -port 7089 -nshrds 3 &
export M3=$!
#bin/server -port 7070 -mdl true &> /proc/20174/fd/1 &
bin/server -port 7070 -mdl true &> shard0.txt &
sleep 2
export L1=$!
bin/server -port 7071 -mdl true &> /dev/null &
export R12=$!
bin/server -port 7072 -mdl true &> /dev/null &
export R13=$!
sleep 2
#bin/server -port 7073 -mport 7088 -mdl true &> /proc/19829/fd/1 &
bin/server -port 7073 -mport 7088 -mdl true &> shard1.txt &
export L2=$!
sleep 2
bin/server -port 7074 -mport 7088 -mdl true &> /dev/null &
export R22=$!
bin/server -port 7075 -mport 7088 -mdl true &> /dev/null &
export R23=$!
sleep 2
#bin/server -port 7073 -mport 7088 -mdl true &> /proc/19829/fd/1 &
bin/server -port 7076 -mport 7089 -mdl true &> shard2.txt &
export L3=$!
sleep 2
bin/server -port 7077 -mport 7089 -mdl true &> /dev/null &
export R32=$!
bin/server -port 7078 -mport 7089 -mdl true &> /dev/null &
export R33=$!
sleep 4
bin/client-ms-test -pid 100 -fo 2 -w 50 -c 3 -k 3 -mdl true &> /proc/7519/fd/1 &
export CLIENT1=$!
bin/client-ms-test -pid 200 -fo 2 -w 50 -c 3 -k 3 -mdl true &> /proc/7893/fd/1 &
export CLIENT2=$!
sleep 10000000000
