#!/bin/bash

cmd="sudo rm -rf /mnt/extra/experiments/2*"
addrId=(0829 1137 1106 1039 0845 0837 1142 1036)
for ((i = 0; i < ${#addrId[@]}; i++)); do
      ssh -AX akalaba@ms${addrId[i]}.utah.cloudlab.us $cmd
    done

