#!/bin/bash

#python3 ./scripts/run_multiple_experiments.py ./experiments/osdi24/mp-3-wide3.json
#wait
#mv experiments/osdi24/results/tput-3/2* experiments/osdi24/results/tput-3/wan/mp_wide3-f1
#rm -rf experiments/osdi24/results/tput-3/wan/mp_wide3-f1/2*/2*/out/client*
#wait

#python3 ./scripts/run_multiple_experiments.py ./experiments/osdi24/mp-3-wide4.json
#wait
#mv experiments/osdi24/results/tput-3/2* experiments/osdi24/results/tput-3/wan/mp_wide4-f1
#rm -rf experiments/osdi24/results/tput-3/wan/mp_wide4-f1/2*/2*/out/client*
#wait

python3 ./scripts/run_multiple_experiments.py ./experiments/osdi24/mp-3-wide.json
wait
mv experiments/osdi24/results/tput-3/2* experiments/osdi24/results/tput-3/wan/mp_wide1-f1
rm -rf experiments/osdi24/results/tput-3/wan/mp_wide1-f1/2*/2*/out/client*
wait

#python3 ./scripts/run_multiple_experiments.py ./experiments/osdi24/mp-3-wide2.json
#wait
#mv experiments/osdi24/results/tput-3/2* experiments/osdi24/results/tput-3/wan/mp_wide2-f1
#rm -rf experiments/osdi24/results/tput-3/wan/mp_wide2-f1/2*/2*/out/client*
#wait
